---
title: "The EPOC-AKI Study"
author: "Alwin Wang, Lisa Toh"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: ["../../resources/references.bib", "../../resources/R-references.bib"]
biblio-style: apalike
link-citations: yes
github-repo: AlwinW/epoc-aki
description: "Evaluation of the Predictive value of short-term Oliguria and minor Creatinine increases for Acute Kidney Injury in ICU"
---

```{r setup}
knitr::opts_chunk$set(echo=TRUE, message=FALSE, cache=TRUE)
rel_path = "../.."
```

# Preface {-}

## Environment set-up {-}

```{r 01_config, include=FALSE, cache=FALSE}
knitr::read_chunk("../../R/01_config.R")
```

1. `R` and `RStudio`

    - This analysis is carried out using `R version 4.0.0 (2020-04-24)`
    - The package `tidyverse version 1.3.0` was extensively used
    - The IDE `RStudio version 1.3.959` was used to help preview this book

2. `R` packages

    - The list of `R` packages used is in `requirements.txt`
    - These are loaded using

    ```{r, load_library_function, echo=FALSE}
    ```

    ```{r environment_setup, warnings = FALSE}
    ```

3. The full session information is presented below

    ```{r sessionInfo}
    sessionInfo()
    ```
